Solution3/src/Solution3.Web/Pages/Index.cshtml.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Solution3.Application.Commands;
using Solution3.Application.Queries;
using Solution3.Application.ViewModels;

namespace Solution3.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;

        public IndexModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public JobStatusViewModel JobStatus { get; set; }

        public async Task OnGetAsync()
        {
            var query = new GetJobDetailsQuery();
            JobStatus = await _mediator.Send(query, CancellationToken.None);
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid? id)
        {
            // ReSharper disable once InvertIf
            if (id.HasValue)
            {
                var command = new CompleteJobCommand(id.Value);
                await _mediator.Send(command, CancellationToken.None);
            }

            return RedirectToPage();
        }
    }
}

Solution3/src/Solution3.Web/Pages/Index.cshtml
@page
@model IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.JobStatus.Status[0].JobId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobStatus.Status[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobStatus.Status[0].Floor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobStatus.Status[0].RoomTypeName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobStatus.Status[0].Status)
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.JobStatus.Status)
            {
                string color;
                switch (item.StatusId)
                {
                    case 1:
                        color = "green";
                        break;
                    case 2:
                        color = "white";
                        break;
                    case 3:
                        color = "yellow";
                        break;
                    case 4:
                        color = "orange";
                        break;
                    default:
                        color = "lightgray";
                        break;
                };
                <tr style="background-color: @color">
                    <td>
                        @Html.DisplayFor(modelItem => item.JobId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Floor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RoomTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @if (item.StatusId == 3 || item.StatusId == 4)
                        {
                            <button type="submit" asp-page-handler="delete" asp-route-id="@item.JobId">Complete Job</button>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

Solution3/src/Solution3.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Maintenance Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Maintenance Web</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", false)
</body>
</html>